### ISSUE TITLE
0.0.6 dependency problem

### ISSUE THREAD

**Issue by mix1009** [Azzeccagarbugli/openai_client#10]
I'm on Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git.
Freshly created an app using flutter create, and added openai_client: ^0.0.6 to pubspec.yaml.

"flutter pub get" fails with:

```
Because every version of flutter_test from sdk depends on meta 1.8.0 and openai_client >=0.0.6 depends on meta ^1.9.0,
  flutter_test from sdk is incompatible with openai_client >=0.0.6.
So, because test_openai depends on both openai_client ^0.0.6 and flutter_test from sdk, version solving failed.

```

**Comment by Azzeccagarbugli** [comment]
#12 fixed this, I will deploy the new version in the _pub.dev_ as soon as possible
