### ISSUE TITLE
Multiple ChatMessages not supported? 

### ISSUE THREAD

**Issue by mix1009** [Azzeccagarbugli/openai_client#11]
How can I pass multiple ChatMessages to OpenAIClient.chat ?
It only accepts one ChatMessage.

```
  final chat = await client.chat
      .create(
          model: 'gpt-3.5-turbo',
          message: const ChatMessage(
            role: 'user',
            content: 'How do you think is Batman dealing with Robin recently?',
          ))
      .data;
```

**Comment by Azzeccagarbugli** [comment]
Hey @mix1009, I'm gonna work on a solution, thanks a lot in advance for spotting this!

**Comment by jimmyff** [comment]
Hi, came here to report the same issue. Seems like a fundamental requirement to work with the api

documentation: https://platform.openai.com/docs/api-reference/chat/create#chat/create-messages
