### ISSUE TITLE
Got Invalid Content-Type header error

### ISSUE THREAD

**Issue by KSH-KOR** [Azzeccagarbugli/openai_client#2]
Hi sir,
I've got an **Invalid Content-Type header** error on OpenAIClient.images.edit() and OpenAIClient.images.variation().
This is the error msg: _Invalid Content-Type header (application/json), expected multipart/form-data. (HINT: If you're using curl, you can pass -H 'Content-Type: multipart/form-data')_
So, this is what I've tried:
1. lib>src>network>request.dart>Request>_createHeaders>
      headers.addAll({
        'Content-Type': 'application/json',
      }); --> 
      headers.addAll({
        'Content-Type': 'multipart/form-data',
      });
Then I got another error: " 'image' is a required property "
I do not know much about HTTP response and request.. but I am trying to learn about it.
Can you give me any advice about fixing that issue?

**Comment by Azzeccagarbugli** [comment]
Hello @KSH-KOR, could you share the snippet of the code giving you the error?

**Comment by Azzeccagarbugli** [comment]
#8 this should fix the issue. Let me know!
