### ISSUE TITLE
Support for functions?

### ISSUE THREAD

**Issue by Wizzel1** [Azzeccagarbugli/openai_client#20]
Are there any plans to add the new functions feature?

**Comment by Azzeccagarbugli** [comment]
> Are there any plans to add the new functions feature?

Hello @Wizzel1 👋

Unfortunately, I don't have much spare time so the project development is stopped for now...

Meanwhile, you could check out this really [cool package](https://pub.dev/packages/dart_openai) that has - basically - everything almost implemented!

Enjoy 🚀

**Comment by Wizzel1** [comment]
@Azzeccagarbugli okay thanks for the quick response, all the best
