### ISSUE TITLE
[Question] Any way I can use OpenAI from Azure?

### ISSUE THREAD

**Issue by timnew** [Azzeccagarbugli/openai_client#22]
Azure Open AI shares a lot of features to the standard OpenAI protocol, but with a few variants: 
* Azure uses a very different type of url, which even include some query string for versioning.
* Azure uses a different auth header (`api-key` instead of normal Bear token)
* Azure don't have organization concept.

**Comment by Azzeccagarbugli** [comment]
Hello @timnew, feel free to clone the code and do the modifications that you need for the porting 🤙
