### ISSUE TITLE
Override the default headers

### ISSUE THREAD

**Issue by dyardy** [Azzeccagarbugli/openai_client#3]
I am hoping you have tried this and have some tips.

I am using the variations end point passing in a file which requires headers of  'Content-Type': 'multipart/form-data' (and not 'application/json')

The problem is that heads are added within the await.request.go() method and application/json is set instead of the multipart/form-data.
` response = await request.go();`

**How can I override the headers used?**

```
  Future<String> createDifferentVariationsWithOpenAI({required File inputImage, int n = 5}) async {
    final Request requestImage = _openAIClient.images.variation(image: inputImage,n: n);

    return _getImagesFromRequest(request: requestImage);
  }

 Future<String> _getImagesFromRequest({required Request request}) async {
    final Images image;
    late final Response response;
    try {
      response = await request.go();

      image = response.get();
    } on StateError catch (_) {
      return response.json['error']['message']; 
    } catch (e) {
      return "error occurred: $e";
    }

    return (image)
        .data
        .map((e) async => e.url)
        .toList()[0];
  }  
```

**Comment by Azzeccagarbugli** [comment]
Hey @dyardy, thanks for opening first of all.

I didn't think about this fallback, I would say that we should pass a custom parameter to the `request.go()` method to override the header.

What's your take on this?

**Comment by dyardy** [comment]
I would suggest that you include tests for getting images and variations and we can go from there.

**Comment by Azzeccagarbugli** [comment]
> I didn't think about this fallback, I would say that we should pass a custom parameter to the `request.go()` method to override the header.

Hey @dyardy, I tried to implement this solution, and it should be working. 

You could try it by installing the package from this brand-new branch in this way: 

```yaml
dependencies:
  openai_client:
    git:
      url: git@github.com:Azzeccagarbugli/openai_client.git
      ref: 3-override-the-default-headers
```
Let me know if it's okay!
